-- Run this file using MySQL Client or Command Line

-- Create the database
CREATE DATABASE IF NOT EXISTS book;

-- Use the created database
USE book;

-- Create the `books` table
CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    author VARCHAR(255),
    description TEXT,
    genres VARCHAR(255),
    goodreads_rating FLOAT,
    amazon_rating FLOAT,
    bookish_rating FLOAT,
    fantastic_fiction_rating FLOAT,
    book_depository_rating FLOAT
);

-- Insert records into the `books` table
INSERT INTO books (title, author, genres, description, goodreads_rating, amazon_rating, bookish_rating, fantastic_fiction_rating, book_depository_rating)
VALUES
('To Kill a Mockingbird', 'Harper Lee', 'Fiction', 'A classic novel that explores racial injustice and moral growth in the American South during the 1930s.', 4.28, 4.7, 4.2, 4.1, 4.5),
('The Great Gatsby', 'F. Scott Fitzgerald', 'Classic, Fiction', 'Set in the Roaring Twenties, this novel explores the decadence and excess of the Jazz Age in America.', 3.91, 4.3, 4.0, 3.8, 4.2),
('1984', 'George Orwell', 'Dystopian, Fiction', 'A chilling vision of a totalitarian regime and the dangers of absolute power.', 4.18, 4.6, 4.4, 4.3, 4.5),
('Pride and Prejudice', 'Jane Austen', 'Classic, Romance', 'A witty exploration of love, social class, and self-discovery.', 4.26, 4.8, 4.5, 4.2, 4.6),
('The Catcher in the Rye', 'J.D. Salinger', 'Classic, Fiction', 'A coming-of-age story about teenage angst and rebellion.', 3.81, 4.1, 3.9, 3.8, 4.0),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy, Adventure', 'A prelude to The Lord of the Rings, exploring Bilbo Baggins unexpected journey.', 4.27, 4.8, 4.6, 4.5, 4.7),
('The Alchemist', 'Paulo Coelho', 'Philosophy, Adventure', 'A philosophical tale of a shepherd seeking his personal legend.', 3.88, 4.5, 4.3, 4.1, 4.4),
('Harry Potter and the Sorcerers Stone', 'J.K. Rowling', 'Fantasy, Young Adult', 'The magical journey of a young wizard discovering his destiny.', 4.47, 4.9, 4.8, 4.6, 4.7),
('The Kite Runner', 'Khaled Hosseini', 'Fiction, Drama', 'A gripping tale of friendship, betrayal, and redemption.', 4.34, 4.7, 4.5, 4.3, 4.6),
('The Da Vinci Code', 'Dan Brown', 'Thriller, Mystery', 'A fast-paced thriller exploring art, religion, and historical secrets.', 3.89, 4.4, 4.2, 4.1, 4.3),
('Moby Dick', 'Herman Melville', 'Adventure', 'An epic tale of obsession and revenge between a whaling captain and a white whale.', 3.52, 4.0, 3.8, 3.7, 4.1),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy, Epic', 'An epic saga of friendship, courage, and the struggle between good and evil.', 4.5, 4.9, 4.8, 4.7, 4.8),
('War and Peace', 'Leo Tolstoy', 'Historical, Epic', 'A masterpiece that interweaves love, war, and family in the backdrop of the Napoleonic era.', 4.11, 4.6, 4.3, 4.5, 4.4),
('Crime and Punishment', 'Fyodor Dostoevsky', 'Philosophical Fiction, Drama', 'A psychological exploration of guilt, morality, and redemption.', 4.26, 4.5, 4.4, 4.3, 4.5),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Philosophical Fiction, Family Drama', 'A profound examination of faith, morality, and human nature through the story of three brothers.', 4.32, 4.6, 4.5, 4.4, 4.4),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 'Magical Realism', 'The multi-generational story of the Buendía family in the fictional town of Macondo.', 4.06, 4.4, 4.2, 4.1, 4.3),
('Brave New World', 'Aldous Huxley', 'Dystopian, Science Fiction', 'A visionary dystopian novel that examines the dehumanizing effects of technology and control.', 3.99, 4.5, 4.3, 4.2, 4.4),
('Jane Eyre', 'Charlotte Brontë', 'Classic, Romance', 'A story of resilience, independence, and love in the face of adversity.', 4.14, 4.6, 4.4, 4.3, 4.4),
('Wuthering Heights', 'Emily Brontë', 'Gothic Fiction, Tragedy', 'A dark and passionate tale of love and revenge set on the moors.', 3.87, 4.4, 4.1, 4.0, 4.3),
('A Tale of Two Cities', 'Charles Dickens', 'Historical, Fiction', 'A dramatic story of love, sacrifice, and revolution in 18th-century France.', 3.85, 4.5, 4.2, 4.1, 4.2),
('Don Quixote', 'Miguel de Cervantes', 'Adventure, Satire', 'A humorous yet profound tale of chivalry and the quest for idealism.', 3.9, 4.3, 4.0, 3.9, 4.1),
('The Picture of Dorian Gray', 'Oscar Wilde', 'Philosophical Fiction, Gothic', 'A cautionary tale about vanity, decadence, and the cost of eternal youth.', 4.08, 4.5, 4.3, 4.2, 4.4),
('Animal Farm', 'George Orwell', 'Political Satire, Allegory', 'An allegorical novella critiquing authoritarian regimes through a story about farm animals.', 3.97, 4.6, 4.4, 4.2, 4.5),
('The Fault in Our Stars', 'John Green', 'Romance, Drama', 'A love story between two teenagers who share a passion for literature and a battle with cancer.', 4.22, 4.6, 4.3, 4.1, 4.5),
('The Hunger Games', 'Suzanne Collins', 'Dystopian, Science Fiction', 'A dystopian story where teenagers must fight to the death in an arena controlled by the government.', 4.33, 4.7, 4.4, 4.1, 4.6),
('The Outsiders', 'S.E. Hinton', 'Fiction, Young Adult', 'A story about the struggles of teenage boys from different social classes in the 1960s.', 4.02, 4.5, 4.3, 4.2, 4.4),
('The Girl on the Train', 'Paula Hawkins', 'Psychological Thriller, Mystery', 'A psychological thriller about a woman who becomes entangled in a missing person investigation.', 4.12, 4.4, 4.1, 4.0, 4.3),
('Gone Girl', 'Gillian Flynn', 'Psychological Thriller, Mystery', 'A twisted and dark mystery about a wife who goes missing and the secrets that unfold about her marriage.', 4.08, 4.5, 4.2, 4.1, 4.4),
('The Help', 'Kathryn Stockett', 'Historical Fiction, Drama', 'A story about the lives of black maids working in white households in the 1960s South.', 4.25, 4.7, 4.5, 4.2, 4.6),
('The Martian', 'Andy Weir', 'Science Fiction, Thriller', 'A gripping story about an astronaut stranded on Mars and his fight for survival.', 4.36, 4.8, 4.6, 4.4, 4.7),
('Big Little Lies', 'Liane Moriarty', 'Fiction, Drama', 'A novel about the lives of three women whose seemingly perfect lives unravel with dark secrets.', 4.13, 4.5, 4.2, 4.1, 4.4),
('Circe', 'Madeline Miller', 'Fantasy, Mythology', 'A retelling of the Greek myth of Circe, a powerful witch who faces challenges and explores her identity.', 4.36, 4.8, 4.7, 4.5, 4.8),
('Where the Crawdads Sing', 'Delia Owens', 'Mystery, Drama', 'A mystery about a young woman living alone in the marshlands of North Carolina and the events leading to a murder investigation.', 4.4, 4.8, 4.6, 4.5, 4.7),
('The Night Circus', 'Erin Morgenstern', 'Fantasy, Romance', 'A magical and mysterious circus where two young illusionists compete for supremacy.', 4.08, 4.5, 4.2, 4.0, 4.3),
('The Road', 'Cormac McCarthy', 'Post-apocalyptic, Fiction', 'A father and son struggle to survive in a desolate world after an unspecified apocalyptic event.', 4.21, 4.7, 4.5, 4.3, 4.6),
('The Secret Garden', 'Frances Hodgson Burnett', 'Childrens Literature, Classic', 'The story of a lonely orphan who finds happiness and adventure in a hidden garden.', 4.13, 4.5, 4.3, 4.2, 4.4),
('The Giver', 'Lois Lowry', 'Dystopian, Young Adult', 'A young boy discovers the truth behind the seemingly perfect society he lives in and the consequences of memory loss.', 4.15, 4.6, 4.4, 4.3, 4.5),
('The Song of Achilles', 'Madeline Miller', 'Historical Fiction, Romance', 'A retelling of the Iliad, focusing on the love story between Achilles and Patroclus.', 4.39, 4.8, 4.7, 4.5, 4.8),
('The Shadow of the Wind', 'Carlos Ruiz Zafón', 'Mystery, Thriller', 'A young boy uncovers dark secrets surrounding a forgotten book and a mysterious author in post-World War II Barcelona.', 4.24, 4.7, 4.5, 4.3, 4.6),
('The Nightingale', 'Kristin Hannah', 'Historical Fiction, Drama', 'The story of two sisters in Nazi-occupied France during World War II and their struggle for survival and resistance.', 4.57, 4.9, 4.8, 4.7, 4.9),
('The Book Thief', 'Markus Zusak', 'Historical Fiction, Drama', 'A young girl living in Nazi Germany steals books and shares them with others while witnessing the horrors of war.', 4.38, 4.8, 4.6, 4.5, 4.7),
('The Silent Patient', 'Alex Michaelides', 'Psychological Thriller, Mystery', 'A psychological thriller about a woman who shoots her husband and then falls mute, with a psychotherapist trying to uncover her secrets.', 4.12, 4.5, 4.2, 4.1, 4.3),
('The 5th Wave', 'Rick Yancey', 'Science Fiction, Dystopian', 'A young girl survives a series of alien invasions that wipe out most of humanity and must fight for survival in a post-apocalyptic world.', 3.98, 4.4, 4.2, 4.1, 4.3),
('Heartstopper', 'Alice Oseman', 'Romance, Humour', 'A graphic novel about two boys, Nick and Charlie, who navigate their way through friendship, love, and self-discovery.', 4.44, 4.60, 4.30, 4.20, 4.50),
('The Maze Runner', 'James Dashner', 'Adventure, Thriller', 'A young adult dystopian science fiction novel following the story of a group of teenagers who wake up in a mysterious maze with no memory.', 3.91, 4.20, 3.80, 3.90, 4.00),
('Twilight', 'Stephenie Meyer', 'Romance, Fantasy, Adventure', 'A young adult vampire-romance novel focusing on the relationship between Bella Swan and Edward Cullen.', 3.61, 4.20, 3.90, 4.00, 4.10),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Crime, Thriller', 'A gripping crime thriller that follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they investigate a wealthy family with dark secrets.', 4.13, 4.40, 4.10, 4.00, 4.20),
('The Silence of the Lambs', 'Thomas Harris', 'Crime, Horror, Thriller', 'A psychological horror-thriller novel that introduces FBI trainee Clarice Starling and her encounters with the brilliant but insane cannibalistic serial killer Dr. Hannibal Lecter.', 4.14, 4.50, 4.30, 4.20, 4.10),
('The Princess Bride', 'William Goldman', 'Fantasy, Adventure, Romance, Humour', 'A classic tale of true love, high adventure, pirates, giants, and miracles.', 4.26, 4.70, 4.40, 4.50, 4.60),
('The Godfather', 'Mario Puzo', 'Crime, Thriller', 'A crime novel that chronicles the Corleone family, led by Vito Corleone, and their mafia empire.', 4.37, 4.80, 4.30, 4.40, 4.70),
('A Game of Thrones', 'George R.R. Martin', 'Fantasy, Adventure', 'The first book in the epic fantasy series, "A Song of Ice and Fire," involving power struggles, alliances, and conflicts in the Seven Kingdoms.', 4.45, 4.60, 4.50, 4.70, 4.80),
('Gone with the Wind', 'Margaret Mitchell', 'Romance, Drama', 'Set against the backdrop of the American Civil War, it follows the life of Scarlett O Hara, a strong-willed Southern belle.', 4.30, 4.70, 4.40, 4.50, 4.60),
('The Name of the Wind', 'Patrick Rothfuss', 'Fantasy, Adventure', 'An epic fantasy novel narrated by Kvothe, a magically gifted young man, as he recalls his life story.', 4.55, 4.70, 4.60, 4.50, 4.80),
('The Haunting of Hill House', 'Shirley Jackson', 'Horror, Thriller', 'A classic horror novel about a paranormal investigator who spends time in a haunted mansion with terrifying consequences.', 3.89, 4.10, 3.80, 3.90, 4.00),
('Bridgerton: The Duke and I', 'Julia Quinn', 'Romance, Humour', 'The first book in a series set in Regency-era London, focusing on the romantic lives of the Bridgerton family.', 4.09, 4.60, 4.20, 4.30, 4.50),
('The Stand', 'Stephen King', 'Horror, Adventure', 'A post-apocalyptic horror novel that depicts a world decimated by a deadly pandemic and the battle between good and evil survivors.', 4.34, 4.60, 4.50, 4.40, 4.70),
('Crazy Rich Asians', 'Kevin Kwan', 'Romance, Humour', 'A comedic romance novel that follows the love life of Rachel Chu and her introduction to the lavish world of Singapores elite.', 3.83, 4.10, 4.00, 3.90, 4.20),
('The Bourne Identity', 'Robert Ludlum', 'Thriller, Adventure', 'A gripping spy thriller that follows Jason Bourne, an amnesiac assassin, as he tries to uncover his identity and evade his enemies.', 4.00, 4.30, 4.20, 4.10, 4.40),
('The Hound of the Baskervilles', 'Arthur Conan Doyle', 'Crime, Mystery, Horror, Adventure', 'A classic detective novel featuring Sherlock Holmes as he investigates a supernatural hound on the moors.', 4.12, 4.50, 4.30, 4.20, 4.40),
('Percy Jackson & the Olympians: The Lightning Thief', 'Rick Riordan', 'Fantasy, Adventure', 'The first book in the series follows Percy Jackson, a demigod, as he embarks on a quest to prevent a war among the gods.', 4.24, 4.70, 4.50, 4.60, 4.80),
('Brida', 'Paulo Coelho', 'Romance, Adventure', 'A novel that tells the story of Brida, a young Irish girl on a journey of self-discovery and spiritual awakening.', 3.49, 4.00, 3.80, 3.90, 4.10),
('A Court of Thorns and Roses', 'Sarah J. Maas', 'Fantasy, Romance, Adventure', 'The first book in a fantasy series following a huntress, Feyre, who is taken to the faerie lands as punishment for killing a wolf.', 4.27, 4.70, 4.50, 4.60, 4.80),
('Dark Places', 'Gillian Flynn', 'Crime, Thriller, Horror', 'A dark and gripping thriller about a woman who investigates the massacre of her family that took place years ago.', 3.93, 4.00, 3.90, 4.10, 4.20),
('The Notebook', 'Nicholas Sparks', 'Romance', 'A heartwarming love story between Noah Calhoun and Allie Nelson, set in the backdrop of the 1940s.', 4.10, 4.40, 4.20, 4.30, 4.50),
('Interview with the Vampire', 'Anne Rice', 'Horror, Fantasy', 'A vampire novel chronicling the life of Louis de Pointe du Lac, a vampire, and his struggles with immortality.', 3.99, 4.20, 4.00, 4.10, 4.30),
('The Lies of Locke Lamora', 'Scott Lynch', 'Fantasy, Adventure, Crime', 'An epic fantasy novel following the exploits of a skilled thief named Locke Lamora in a city of crime and intrigue.', 4.30, 4.60, 4.50, 4.40, 4.70),
('One for the Money', 'Janet Evanovich', 'Crime, Humour', 'The first book in the Stephanie Plum series, featuring a bounty hunter navigating crime in Trenton, New Jersey.', 4.03, 4.10, 4.00, 4.20, 4.40),
('Red Dragon', 'Thomas Harris', 'Crime, Horror, Thriller', 'A psychological thriller featuring FBI profiler Will Graham as he pursues a serial killer named "The Tooth Fairy."', 4.02, 4.30, 4.10, 4.20, 4.40),
('The Princess Diaries', 'Meg Cabot', 'Romance, Humour', 'A young adult series following the life of Mia Thermopolis, a teenage girl who discovers she is the heir to a small European principality.', 3.77, 4.00, 3.90, 4.10, 4.20),
('The Blade Itself', 'Joe Abercrombie', 'Fantasy, Adventure', 'The first book in The First Law Trilogy, a dark fantasy series following flawed characters in a world of war, politics, and magic.', 4.14, 4.50, 4.30, 4.40, 4.60),
('My Sister, the Serial Killer', 'Oyinkan Braithwaite', 'Crime, Humour', 'A darkly comedic thriller about a Nigerian woman dealing with her sister who has a habit of killing her boyfriends.', 3.77, 4.00, 3.90, 4.10, 4.20),
('The Ocean at the End of the Lane', 'Neil Gaiman', 'Fantasy, Horror', 'A dark fantasy novel that blends magical realism, horror, and a coming-of-age narrative.', 4.02, 4.30, 4.10, 4.20, 4.40),
('In Cold Blood', 'Truman Capote', 'Crime, Non-fiction', 'A true crime novel about the brutal murder of a Kansas family and the investigation that followed.', 4.03, 4.40, 4.10, 4.20, 4.30),
('Jurassic Park', 'Michael Crichton', 'Adventure, Thriller', 'A science fiction thriller that explores the consequences of cloning dinosaurs for a theme park and the chaos that ensues.', 4.00, 4.20, 4.10, 4.00, 4.30),
('The Girl Who Played with Fire', 'Stieg Larsson', 'Crime, Thriller', 'The second book in the Millennium series, following journalist Mikael Blomkvist and hacker Lisbeth Salander as they uncover a dark conspiracy.', 4.23, 4.40, 4.20, 4.30, 4.50),
('A Man Called Ove', 'Fredrik Backman', 'Humour, Romance', 'A heartwarming tale about an ill-tempered yet charming man named Ove and the unexpected friendships that change his life.', 4.36, 4.60, 4.40, 4.50, 4.70),
('Me Before You', 'Jojo Moyes', 'Romance, Drama', 'A romantic novel about the relationship between a young woman and a paralyzed man she cares for.', 4.27, 4.50, 4.30, 4.40, 4.60),
('The Graveyard Book', 'Neil Gaiman', 'Fantasy, Horror', 'A supernatural tale about a boy raised by ghosts in a graveyard.', 4.13, 4.40, 4.20, 4.30, 4.50),
('Neverwhere', 'Neil Gaiman', 'Fantasy, Adventure', 'A fantasy novel set in an alternate London full of magical and fantastical creatures.', 4.18, 4.50, 4.30, 4.40, 4.60),
('The Husbands Secret', 'Liane Moriarty', 'Crime, Thriller', 'A thriller exploring the consequences when a woman discovers a letter addressed to her from her husband, to be opened only upon his death.', 3.94, 4.10, 3.90, 4.00, 4.20),
('The Hitchhikers Guide to the Galaxy', 'Douglas Adams', 'Humour, Adventure', 'A comedic science fiction series following the adventures of Arthur Dent after Earths destruction.', 4.22, 4.40, 4.20, 4.30, 4.50),
('The Girl in the Ice', 'Robert Bryndza', 'Crime, Thriller', 'A crime thriller featuring detective Erika Foster as she investigates the murder of a young socialite.', 4.04, 4.20, 4.00, 4.10, 4.30),
('The Gentleman Bastard Series', 'Scott Lynch', 'Fantasy, Crime, Adventure', 'A series following a group of skilled con artists known as the Gentleman Bastards in a fantasy world.', 4.33, 4.60, 4.50, 4.40, 4.70),
('Eleanor Oliphant Is Completely Fine', 'Gail Honeyman', 'Humour, Romance', 'A heartwarming and humorous novel about Eleanor Oliphant, a socially awkward woman, and her journey towards self-discovery.', 4.24, 4.50, 4.30, 4.40, 4.60),
('The Girl with All the Gifts', 'M.R. Carey', 'Horror, Thriller', 'A post-apocalyptic horror novel featuring a young girl with unique abilities in a world plagued by a fungal infection.', 4.02, 4.30, 4.10, 4.20, 4.40),
('Bird Box', 'Josh Malerman', 'Horror, Thriller', 'A chilling tale set in a world where seeing something unknown drives people to deadly violence, forcing survivors to live blindfolded.', 4.02, 4.30, 4.10, 4.20, 4.40),
('Classroom of the Elite', 'Shōgo Kinugasa', 'Thriller', 'A light novel series set in an elite high school where students are trained to become future leaders.', 4.12, 4.50, 4.30, 4.40, 4.60),
('My Happy Marriage', 'Miki Yoshikawa', 'Romance, Humour', 'A romantic comedy manga exploring the ups and downs of married life.', 4.20, 4.60, 4.40, 4.50, 4.70),
('Who Made Me a Princess', 'Pluto', 'Fantasy, Romance', 'A webtoon about a girl who finds herself reincarnated as a princess in a deadly and cruel imperial court.', 4.52, 4.80, 4.60, 4.70, 4.90),
('Where Rainbows End', 'Cecelia Ahern', 'Romance', 'The story of two childhood friends whose lives take different paths but whose bond remains strong through the years.', 4.09, 4.40, 4.20, 4.30, 4.50),
('The Shining', 'Stephen King', 'Horror, Thriller', 'A terrifying story of isolation, madness, and supernatural horror in a haunted hotel.', 4.22, 4.6, 4.5, 4.3, 4.4);
